//
//  LocalizationConstants.h
//  Blockchain
//
//  Created by Tim Lee on 8/6/14.
//  Copyright (c) 2014 Qkos Services Ltd. All rights reserved.
//
#import <Foundation/Foundation.h>

#define BC_STRING_ANY_ADDRESS NSLocalizedString(@"Any address", nil)
#define BC_STRING_ARGUMENT_ADDRESSES NSLocalizedString(@"%d addresses", nil)
#define BC_STRING_ARGUMENT_ADDRESS NSLocalizedString(@"%d address", nil)
#define BC_STRING_NO_ADDRESSES_WITH_SPENDABLE_BALANCE_ABOVE_OR_EQUAL_TO_DUST NSLocalizedString(@"You have no addresses with a spendable balance greater than or equal to the required dust threshold.", nil)
#define BC_STRING_SOME_FUNDS_CANNOT_BE_TRANSFERRED_AUTOMATICALLY NSLocalizedString(@"Some funds cannot be transferred automatically.", nil)

#define BC_STRING_ENTER_BITCOIN_ADDRESS_OR_SELECT NSLocalizedString(@"Enter Bitcoin address or select", nil);
#define BC_STRING_YOU_MUST_ENTER_DESTINATION_ADDRESS NSLocalizedString(@"You must enter a destination address", nil)
#define BC_STRING_INVALID_TO_BITCOIN_ADDRESS NSLocalizedString(@"Invalid to bitcoin address", nil)
#define BC_STRING_FROM_TO_DIFFERENT NSLocalizedString(@"From and destination have to be different", nil)
#define BC_STRING_FROM_TO_ADDRESS_DIFFERENT NSLocalizedString(@"From and destination address have to be different", nil)
#define BC_STRING_INVALID_SEND_VALUE NSLocalizedString(@"Invalid Send Value", nil)

#define BC_STRING_SIGNING_INPUTS NSLocalizedString(@"Signing Inputs", nil)
#define BC_STRING_SIGNING_INPUT NSLocalizedString(@"Signing Input %d", nil)
#define BC_STRING_FINISHED_SIGNING_INPUTS NSLocalizedString(@"Finished Signing Inputs", nil)
#define BC_STRING_TRANSFER_ALL_FROM_ADDRESS_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferring all funds: Address %i of %i", nil)
#define BC_STRING_TRANSFER_ALL_CALCULATING_AMOUNTS_AND_FEES_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Calculating: Address %d of %d", nil)

#define BC_STRING_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Add to Address book?", nil)
#define BC_STRING_NO NSLocalizedString(@"No", nil)
#define BC_STRING_YES NSLocalizedString(@"Yes", nil)
#define BC_STRING_SEND NSLocalizedString(@"Send", nil)
#define BC_STRING_NO_AVAILABLE_FUNDS NSLocalizedString(@"You have no available funds to send from this address", nil)
#define BC_STRING_MUST_BE_ABOVE_OR_EQUAL_TO_DUST_THRESHOLD NSLocalizedString(@"Amount must be greater than or equal to the dust threshold (%lld Satoshi)", nil)
#define BC_STRING_RECEIVE NSLocalizedString(@"Receive", nil)
#define BC_STRING_INFORMATION_RECEIVE NSLocalizedString(@"For increased privacy, we generate a unique address for every payment. All addresses generated in your wallet can still receive funds, even if they no longer appear under Receive.", nil)
#define BC_STRING_TRANSACTIONS NSLocalizedString(@"Transactions", nil)
#define BC_STRING_LOAD_MORE_TRANSACTIONS NSLocalizedString(@"Load More Transactions", nil)
#define BC_STRING_SENDING_TRANSACTION NSLocalizedString(@"Sending Transaction", nil)
#define BC_STRING_USE_TOTAL_AVAILABLE_MINUS_FEE_ARGUMENT NSLocalizedString(@"Use total available minus fee: %@", nil)

#define BC_STRING_SUCCESS NSLocalizedString(@"Success", nil)
#define BC_STRING_PAYMENT_SENT NSLocalizedString(@"Payment Sent!", nil)
#define BC_STRING_PAYMENTS_SENT NSLocalizedString(@"Payments Sent", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT NSLocalizedString(@"Transferred funds from %d %@", nil)
#define BC_STRING_PAYMENT_TRANSFERRED_FROM_ARGUMENT_ARGUMENT_OUTPUTS_ARGUMENT_ARGUMENT_TOO_SMALL NSLocalizedString(@"Transferred funds from %d %@. Outputs for %d %@ were too small.", nil)
#define BC_STRING_PAYMENT_ASK_TO_ARCHIVE_TRANSFERRED_ADDRESSES NSLocalizedString(@"Would you like to archive the addresses used?", nil)
#define BC_STRING_PAYMENT_RECEIVED NSLocalizedString(@"Payment Received", nil)
#define BC_STRING_RECEIVE_SCREEN_INSTRUCTIONS NSLocalizedString(@"Tap to copy this address. Share it with the sender via email or text.", nil)

#define BC_STRING_CONFIRM_PAYMENT NSLocalizedString(@"Confirm Payment", nil)
#define BC_STRING_ADJUST_FEE NSLocalizedString(@"Adjust Fee", nil)
#define BC_STRING_ASK_TO_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Would you like to add the bitcoin address %@ to your address book?", nil)
#define BC_STRING_ARGUMENT_COPIED_TO_CLIPBOARD NSLocalizedString(@"%@ copied to clipboard", nil)
#define BC_STRING_COPIED_TO_CLIPBOARD NSLocalizedString(@"Copied to clipboard", nil)
#define BC_STRING_CONFIRM_PAYMENT_OF NSLocalizedString(@"To: %@\n%@\nTotal Amount: %@\nFee: %@\n(%@)", nil)
#define BC_STRING_SEND_FROM NSLocalizedString(@"Send from...", nil)
#define BC_STRING_SEND_TO NSLocalizedString(@"Send to...", nil)
#define BC_STRING_RECEIVE_TO NSLocalizedString(@"Receive to...", nil)
#define BC_STRING_WHERE NSLocalizedString(@"Where", nil)
#define BC_STRING_CONFIRM_SWEEP_TITLE NSLocalizedString(@"Use all funds", nil)
#define BC_STRING_CONFIRM_SWEEP_MESSAGE_WANT_TO_SEND_ARGUMENT_BALANCE_MINUS_FEE_ARGUMENT_ARGUMENT_SEND_ARGUMENT NSLocalizedString(@"The amount you want to send (%@) is greater than the maximum amount you can spend minus the fee (%@ - %@). Would you like to send %@?", nil)

#define BC_STRING_YOU_MUST_ENTER_A_LABEL NSLocalizedString(@"You must enter a label", nil)
#define BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR NSLocalizedString(@"Label must have less than 18 characters", nil)
#define BC_STRING_LABEL_MUST_BE_ALPHANUMERIC NSLocalizedString(@"Label must contain letters and numbers only", nil)
#define BC_STRING_UNARCHIVE NSLocalizedString(@"Unarchive", nil)
#define BC_STRING_ARCHIVE NSLocalizedString(@"Archive", nil)
#define BC_STRING_ARCHIVING_ADDRESSES NSLocalizedString(@"Archiving addresses", nil)
#define BC_STRING_ARCHIVED NSLocalizedString(@"Archived", nil)
#define BC_STRING_NO_LABEL NSLocalizedString(@"No Label", nil)
#define BC_STRING_TRANSACTIONS_COUNT NSLocalizedString(@"%d Transactions", nil)
#define BC_STRING_LOADING_EXTERNAL_PAGE NSLocalizedString(@"Loading External Page", nil)

#define BC_STRING_PASSWORD_NOT_STRONG_ENOUGH NSLocalizedString(@"Your password is not strong enough. Please choose a different password.", nil)
#define BC_STRING_PASSWORD_MUST_BE_LESS_THAN_OR_EQUAL_TO_255_CHARACTERS NSLocalizedString(@"Password must be less than or equal to 255 characters", nil)
#define BC_STRING_PASSWORDS_DO_NOT_MATCH NSLocalizedString(@"Passwords do not match", nil)
#define BC_STRING_PASSWORD_MUST_BE_DIFFERENT_FROM_YOUR_EMAIL NSLocalizedString(@"Password must be different from your email", nil)
#define BC_STRING_NEW_PASSWORD_MUST_BE_DIFFERENT NSLocalizedString(@"New password must be different", nil)
#define BC_STRING_NEW_PASSWORD_MUST_BE_DIFFERENT_FROM_HINT NSLocalizedString(@"New password must be different from your password hint", nil)
#define BC_STRING_PLEASE_PROVIDE_AN_EMAIL_ADDRESS NSLocalizedString(@"Please provide an email address.", nil)
#define BC_STRING_PLEASE_VERIFY_EMAIL_ADDRESS_FIRST NSLocalizedString(@"Please verify your email address first.", nil)
#define BC_STRING_INVALID_EMAIL_ADDRESS NSLocalizedString(@"Invalid email address.", nil)
#define BC_STRING_DID_CREATE_NEW_WALLET_DETAIL NSLocalizedString(@"Before accessing your wallet, please choose a pin number to use to unlock your wallet. It's important you remember this pin as it cannot be reset or changed without first unlocking the app.", nil)
#define BC_STRING_DID_CREATE_NEW_WALLET_TITLE NSLocalizedString(@"Your wallet was successfully created.", nil)
#define BC_STRING_MY_BITCOIN_WALLET NSLocalizedString(@"My Bitcoin Wallet", nil)
#define BC_STRING_PASSWORD_STRENGTH_WEAK NSLocalizedString(@"Weak", nil)
#define BC_STRING_PASSWORD_STRENGTH_REGULAR NSLocalizedString(@"Regular", nil)
#define BC_STRING_PASSWORD_STRENGTH_NORMAL NSLocalizedString(@"Normal", nil)
#define BC_STRING_PASSWORD_STRENGTH_STRONG NSLocalizedString(@"Strong", nil)

#define BC_STRING_UNCONFIRMED NSLocalizedString(@"Unconfirmed", nil)
#define BC_STRING_COUNT_CONFIRMATIONS NSLocalizedString(@"%d Confirmations", nil)

#define BC_STRING_TRANSFERRED NSLocalizedString(@"Transferred", nil)
#define BC_STRING_RECEIVED NSLocalizedString(@"Received", nil)
#define BC_STRING_SENT NSLocalizedString(@"Sent", nil)

#define BC_STRING_ERROR NSLocalizedString(@"Error", nil)
#define BC_STRING_INVALID_AUTHENTICATION_TYPE NSLocalizedString(@"Invalid two-factor authentication type", nil)
#define BC_STRING_ERROR_LOADING_WALLET_IDENTIFIER_FROM_KEYCHAIN NSLocalizedString(@"An error was encountered retrieving your wallet identifier from the keychain. Please close the application and try again.", nil)
#define BC_STRING_ERROR_LOADING_WALLET NSLocalizedString(@"Unable to load wallet due to no server response. You may be offline or Blockchain is experiencing difficulties. Please try again later.", nil)

#define BC_STRING_INFORMATION NSLocalizedString(@"Information", nil)
#define BC_STRING_LEARN_MORE NSLocalizedString(@"Learn More", nil)
#define BC_STRING_IMPORT_PRIVATE_KEY NSLocalizedString(@"Import Private Key", nil)
#define BC_STRING_DECRYPTING_PRIVATE_KEY NSLocalizedString(@"Decrypting Private Key", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY NSLocalizedString(@"Extended Public Key", nil)

#define BC_STRING_UNSUPPORTED_PRIVATE_KEY_FORMAT NSLocalizedString(@"Unsupported Private Key Format", nil)
#define BC_STRING_SCAN_PAIRING_CODE NSLocalizedString(@"Scan Pairing Code", nil)
#define BC_STRING_PARSING_PAIRING_CODE NSLocalizedString(@"Parsing Pairing Code", nil)
#define BC_STRING_INVALID_PAIRING_CODE NSLocalizedString(@"Invalid Pairing Code", nil)

#define BC_STRING_INSUFFICIENT_FUNDS NSLocalizedString(@"Insufficient Funds", nil)
#define BC_STRING_PLEASE_SELECT_DIFFERENT_ADDRESS NSLocalizedString(@"Please select a different address to send from.", nil)

#define BC_STRING_OK NSLocalizedString(@"OK", nil)
#define BC_STRING_OPEN_MAIL_APP NSLocalizedString(@"Open Mail App", nil)
#define BC_STRING_FAILED_TO_LOAD_WALLET_TITLE NSLocalizedString(@"Failed To Load Wallet", nil)

#define BC_STRING_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection.", nil)
#define BC_STRING_REQUEST_FAILED_PLEASE_CHECK_INTERNET_CONNECTION NSLocalizedString(@"Request failed. Please check your internet connection.", nil)
#define BC_STRING_SOMETHING_WENT_WRONG_CHECK_INTERNET_CONNECTION NSLocalizedString(@"An error occurred while updating your spendable balance. Please check your internet connection and try again.", nil)
#define BC_STRING_TIMED_OUT NSLocalizedString(@"Connection timed out. Please check your internet connection.", nil)
#define BC_STRING_EMPTY_RESPONSE NSLocalizedString(@"Empty response from server.", nil)
#define BC_STRING_INVALID_RESPONSE NSLocalizedString(@"Invalid server response. Please check your internet connection.", nil)
#define BC_STRING_MAINTENANCE_MODE NSLocalizedString(@"Blockchain is currently down for maintenance. Please try again later.", nil)

#define BC_STRING_FAILED_TO_LOAD_WALLET_DETAIL NSLocalizedString(@"An error was encountered loading your wallet. You may be offline or Blockchain is experiencing difficulties. Please close the application and try again later or re-pair your device.", nil)
#define BC_STRING_FORGET_WALLET NSLocalizedString(@"Forget Wallet", nil)

#define BC_STRING_CLOSE_APP NSLocalizedString(@"Close App", nil)
#define BC_STRING_PRIVATE_KEY_ENCRYPTED_DESCRIPTION NSLocalizedString(@"The private key you are attempting to import is encrypted. Please enter the password below.", nil)

#define BC_STRING_NO_PASSWORD_ENTERED NSLocalizedString(@"No Password Entered", nil)
#define BC_STRING_SECOND_PASSWORD_INCORRECT NSLocalizedString(@"Second Password Incorrect", nil)

#define BC_STRING_ACTION_REQUIRES_SECOND_PASSWORD NSLocalizedString(@"This action requires the second password for your bitcoin wallet. Please enter it below and press continue.", nil)
#define BC_STRING_INVALID_GUID NSLocalizedString(@"Invalid Wallet ID", nil)

#define BC_STRING_INVALID_SHARED_KEY NSLocalizedString(@"Invalid Shared Key", nil)
#define BC_STRING_ENTER_YOUR_CHARACTER_WALLET_IDENTIFIER NSLocalizedString(@"Please enter your 36 character wallet identifier correctly. It can be found in the welcome email on startup.", nil)
#define BC_STRING_INVALID_IDENTIFIER NSLocalizedString(@"Invalid Identifier", nil)

#define BC_STRING_DISABLE_TWO_FACTOR NSLocalizedString(@"You must have two-factor authentication disabled to pair manually.", nil)
#define BC_STRING_WALLET_PAIRED_SUCCESSFULLY_DETAIL NSLocalizedString(@"Before accessing your wallet, please choose a pin number to use to unlock your wallet. It's important you remember this pin as it cannot be reset or changed without first unlocking the app.", nil)
#define BC_STRING_WALLET_PAIRED_SUCCESSFULLY_TITLE NSLocalizedString(@"Wallet Paired Successfully.", nil)
#define BC_STRING_WATCH_ONLY NSLocalizedString(@"Watch Only", nil)
#define BC_STRING_WATCH_ONLY_RECEIVE_WARNING NSLocalizedString(@"You are about to receive bitcoin to a watch-only address. You can only spend these funds if you have access to the private key. Continue?", nil)
#define BC_STRING_USER_DECLINED NSLocalizedString(@"User Declined", nil)
#define BC_STRING_CHANGE_PIN NSLocalizedString(@"Change PIN", nil)
#define BC_STRING_ADDRESS NSLocalizedString(@"Address", nil)
#define BC_STRING_ADDRESSES NSLocalizedString(@"Addresses", nil)
#define BC_STRING_SETTINGS NSLocalizedString(@"Settings", nil)
#define BC_STRING_BACKUP NSLocalizedString(@"Backup", nil)
#define BC_STRING_SECURITY_CENTER NSLocalizedString(@"Security Center", nil)
#define BC_STRING_ADD_EMAIL NSLocalizedString(@"Add Email", nil)
#define BC_STRING_LOGOUT NSLocalizedString(@"Logout", nil)
#define BC_STRING_REALLY_LOGOUT NSLocalizedString(@"Do you really want to log out?", nil)

#define BC_STRING_WARNING NSLocalizedString(@"Warning!!!", nil)
#define BC_STRING_FORGET_WALLET_DETAILS NSLocalizedString(@"This will erase all wallet data on this device. Please confirm you have your wallet information saved elsewhere otherwise any bitcoin in this wallet will be inaccessible!!", nil)
#define BC_STRING_CANCEL NSLocalizedString(@"Cancel", nil)
#define BC_STRING_CANCELLING NSLocalizedString(@"Cancelling", nil)
#define BC_STRING_HOW_WOULD_YOU_LIKE_TO_PAIR NSLocalizedString(@"How would you like to pair?", nil)
#define BC_STRING_MANUALLY NSLocalizedString(@"Manually", nil)
#define BC_STRING_AUTOMATICALLY NSLocalizedString(@"Automatically", nil)
#define BC_STRING_PIN_VALIDATION_ERROR NSLocalizedString(@"PIN Validation Error", nil)
#define BC_STRING_PLEASE_CHOOSE_ANOTHER_PIN NSLocalizedString(@"Please choose another PIN", nil)
#define BC_PIN_NO_MATCH NSLocalizedString(@"PINs do not match", nil)

#define BC_STRING_PIN_VALIDATION_ERROR_DETAIL NSLocalizedString(@"An error occurred validating your PIN code with the remote server. You may be offline or Blockchain may be experiencing difficulties. Would you like retry validation or instead enter your password manually?", nil)
#define BC_STRING_ENTER_PASSWORD NSLocalizedString(@"Enter Password", nil)
#define BC_STRING_ENTER_PIN NSLocalizedString(@"Enter PIN", nil)
#define BC_STRING_PLEASE_ENTER_PIN NSLocalizedString(@"Please enter your PIN", nil)
#define BC_STRING_PLEASE_ENTER_NEW_PIN NSLocalizedString(@"Please enter a new PIN", nil)
#define BC_STRING_CONFIRM_PIN NSLocalizedString(@"Confirm your PIN", nil)
#define BC_STRING_INCORRECT_PIN_RETRY NSLocalizedString(@"Incorrect PIN. Please retry.", nil)
#define RETRY_VALIDATION NSLocalizedString(@"Retry Validation", nil)
#define BC_STRING_PIN_VALIDATION_CANNOT_BE_COMPLETED NSLocalizedString(@"PIN Validation cannot be completed. Please enter your wallet password manually.", nil)
#define BC_STRING_PIN_RESPONSE_OBJECT_SUCCESS_LENGTH_0 NSLocalizedString(@"PIN Response Object success length 0", nil)
#define BC_STRING_DECRYPTED_PIN_PASSWORD_LENGTH_0 NSLocalizedString(@"Decrypted PIN Password length 0", nil)
#define BC_STRING_CANNOT_SAVE_PIN_CODE_WHILE NSLocalizedString(@"Cannot save PIN Code while wallet is not initialized or password is null", nil)
#define BC_STRING_INVALID_STATUS_CODE_RETURNED NSLocalizedString(@"Invalid Status Code Returned %@", nil)
#define BC_STRING_PIN_RESPONSE_OBJECT_KEY_OR_VALUE_LENGTH_0 NSLocalizedString(@"PIN Response Object key or value length 0", nil)
#define BC_STRING_PIN_ENCRYPTED_STRING_IS_NIL NSLocalizedString(@"PIN Encrypted String is nil", nil)
#define BC_STRING_PIN_SAVED_SUCCESSFULLY NSLocalizedString(@"PIN Saved Successfully", nil)
#define BC_STRING_WARNING_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_PIN_COMMON_CODE_WARNING_MESSAGE NSLocalizedString(@"The PIN you have selected is extremely common and may be easily guessed by someone with access to your phone within 3 tries. Would you like to use this PIN anyway?", nil)
#define BC_STRING_TRY_AGAIN NSLocalizedString(@"Try again", nil)

#define BC_STRING_PAYMENT_REQUEST_ARGUMENT_ARGUMENT NSLocalizedString(@"Please send %@ to bitcoin address.\n%@", nil)
#define BC_STRING_AMOUNT NSLocalizedString(@"Amount", nil)
#define BC_STRING_PAYMENT_REQUEST_HTML NSLocalizedString(@"Please send payment to bitcoin address (<a href=\"https://blockchain.info/wallet/bitcoin-faq\">help?</a>): %@", nil)
#define BC_STRING_PAYMENT_REQUEST_SUBJECT NSLocalizedString(@"Bitcoin payment request", nil)
#define BC_STRING_CLOSE NSLocalizedString(@"Close", nil)

#define BC_STRING_CREATE NSLocalizedString(@"Create", nil)
#define BC_STRING_NAME NSLocalizedString(@"Name", nil)
#define BC_STRING_EDIT NSLocalizedString(@"Edit", nil)
#define BC_STRING_LABEL NSLocalizedString(@"Label", nil)

#define BC_STRING_DONE NSLocalizedString(@"Done", nil)
#define BC_STRING_SAVE NSLocalizedString(@"Save", nil)
#define BC_STRING_CREATE_WALLET NSLocalizedString(@"Create Wallet", nil)

#define BC_STRING_ACCOUNTS NSLocalizedString(@"Accounts", nil)
#define BC_STRING_TOTAL_BALANCE NSLocalizedString(@"Total Balance", nil)
#define BC_STRING_IMPORTED_ADDRESSES NSLocalizedString(@"Imported Addresses", nil)
#define BC_STRING_IMPORTED_ADDRESSES_ARCHIVED NSLocalizedString(@"Imported Addresses (Archived)", nil)

#define BC_STRING_UPGRADE_TO_HD NSLocalizedString(@"Upgrade to HD", nil)
#define BC_STRING_UPGRADE_TO_V3 NSLocalizedString(@"Upgrade to V3", nil)

#define BC_STRING_ADDRESS_BOOK NSLocalizedString(@"Address book", nil)

#define BC_STRING_LOADING_VERIFYING NSLocalizedString (@"Verifying", nil)
#define BC_STRING_LOADING_DOWNLOADING_WALLET NSLocalizedString(@"Downloading Wallet", nil)
#define BC_STRING_LOADING_DECRYPTING_WALLET NSLocalizedString(@"Decrypting Wallet", nil)
#define BC_STRING_LOADING_LOADING_TRANSACTIONS NSLocalizedString(@"Loading transactions", nil)
#define BC_STRING_LOADING_LOADING_BUILD_HD_WALLET NSLocalizedString(@"Initializing Wallet", nil)
#define BC_STRING_LOADING_CHECKING_WALLET_UPDATES NSLocalizedString(@"Checking for Wallet updates", nil)
#define BC_STRING_LOADING_CREATING_HD_WALLET NSLocalizedString(@"Creating HD Wallet", nil)
#define BC_STRING_LOADING_CREATING_V3_WALLET NSLocalizedString(@"Creating V3 Wallet", nil)
#define BC_STRING_LOADING_CREATING NSLocalizedString(@"Creating", nil)
#define BC_STRING_LOADING_CREATING_WALLET NSLocalizedString(@"Creating new Wallet", nil)
#define BC_STRING_LOADING_IMPORT_KEY NSLocalizedString(@"Importing key", nil)
#define BC_STRING_LOADING_PROCESSING_KEY NSLocalizedString(@"Processing key", nil)
#define BC_STRING_LOADING_CREATING_NEW_ADDRESS NSLocalizedString(@"Creating new address", nil)
#define BC_STRING_LOADING_SYNCING_WALLET NSLocalizedString(@"Syncing Wallet", nil)
#define BC_STRING_IDENTIFIER NSLocalizedString(@"Identifier", nil)

#define BC_STRING_MERCHANT_MAP NSLocalizedString(@"Merchant Map", nil)
#define BC_STRING_MERCHANT NSLocalizedString(@"Merchant", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_TITLE NSLocalizedString(@"Enable Location Services", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location.", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE_GLOBALLY_IOS_8_AND_ABOVE NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location. You can enable access in Settings->Privacy->Location Services", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE_GLOBALLY_IOS_7 NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location. You can enable access in Settings->Privacy->Location->Location Services", nil)
#define BC_STRING_GO_TO_SETTINGS NSLocalizedString(@"Go to Settings", nil)

#define BC_STRING_SUPPORT NSLocalizedString(@"Support", nil)
#define BC_STRING_OPEN_ARGUMENT NSLocalizedString(@"Open %@?", nil)
#define BC_STRING_LEAVE_APP NSLocalizedString(@"You will be leaving the app.", nil)

#define BC_STRING_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_TRANSACTION NSLocalizedString(@"Transaction", nil)
#define BC_STRING_AUTOMATIC_PAIRING NSLocalizedString(@"Automatic Pairing", nil)
#define BC_STRING_MANUAL_PAIRING NSLocalizedString(@"Manual Pairing", nil)
#define BC_STRING_MANUAL_PAIRING_AUTHORIZATION_REQUIRED_TITLE NSLocalizedString(@"Authorization Required", nil)
#define BC_STRING_MANUAL_PAIRING_AUTHORIZATION_REQUIRED_MESSAGE NSLocalizedString(@"Please check your email. If you have already verified a login attempt, you should log in via our web wallet and pair your phone by scanning the QR code under Settings -> Wallet Information.", nil)
#define BC_STRING_PASSWORD_REQUIRED NSLocalizedString(@"Password Required", nil)
#define BC_STRING_INCORRECT_PASSWORD NSLocalizedString(@"Incorrect password", nil)
#define BC_STRING_SECOND_PASSWORD_REQUIRED NSLocalizedString(@"Second Password Required", nil)
#define BC_STRING_CREATE_NEW_WALLET NSLocalizedString(@"Create New Wallet", nil)
#define BC_STRING_REQUEST_AMOUNT NSLocalizedString(@"Request Amount", nil)
#define BC_STRING_REQUEST NSLocalizedString(@"Request", nil)
#define BC_STRING_LABEL_ADDRESS NSLocalizedString(@"Label Address", nil)
#define BC_STRING_SCAN_QR_CODE NSLocalizedString(@"Scan QR Code", nil)
#define BC_STRING_SCAN_PRIVATE_KEY NSLocalizedString(@"Scan Private Key", nil)
#define BC_STRING_IMPORT_ADDRESS NSLocalizedString(@"Import address", nil)
#define BC_STRING_CONTINUE NSLocalizedString(@"Continue", nil)

#define BC_STRING_LOG_IN_TO_WALLET NSLocalizedString(@"Log in to my Wallet", nil)
#define BC_STRING_LOGIN_EXISTING_WALLET NSLocalizedString(@"Login existing Wallet", nil)
#define BC_STRING_RECOVER_FUNDS NSLocalizedString(@"Recover Funds", nil)
#define BC_STRING_RECOVER_FUNDS_ONLY_IF_FORGOT_CREDENTIALS NSLocalizedString(@"You should always pair or login if you have access to your Wallet ID and password. Recovering your funds will create a new Wallet ID. Would you like to continue?", nil)

#define BC_STRING_COPY_ADDRESS NSLocalizedString(@"Copy Address", nil)
#define BC_STRING_ARCHIVE_ADDRESS NSLocalizedString(@"Archive Address", nil)
#define BC_STRING_UNARCHIVE_ADDRESS NSLocalizedString(@"Unarchive Address", nil)

#define BC_STRING_AT_LEAST_ONE_ACTIVE_ADDRESS NSLocalizedString(@"You must leave at least one active address", nil)

#define BC_STRING_UPGRADE_TEXT NSLocalizedString(@"We've designed a whole new\nwallet experience for you", nil)
#define BC_STRING_UPGRADE_FEATURES_WHATS_BETTER NSLocalizedString(@"The upgrade takes just a second and your bitcoin and history will be safe. Here is what’s better:", nil)
#define BC_STRING_UPGRADE_FEATURES_REDESIGNED_USER_EXPERIENCE NSLocalizedString(@"Completely updated design and user experience", nil)
#define BC_STRING_UPGRADE_FEATURES_ROBUST_SECURITY_CENTER NSLocalizedString(@"Robust security center", nil)
#define BC_STRING_UPGRADE_FEATURES_ENHANCED_PRIVACY NSLocalizedString(@"Enhanced Privacy", nil)
#define BC_STRING_UPGRADE_FEATURES_SIMPLIFIED_BACKUP NSLocalizedString(@"Simplified backup and recovery", nil)
#define BC_STRING_UPGRADE_FEATURES_CUSTOMIZED_FUND_MANAGEMENT NSLocalizedString(@"Customized fund management", nil)
#define BC_STRING_UPGRADE_FEATURES_SHARED_COIN_NOT_SUPPORTED NSLocalizedString(@"Shared Coin is not supported at this time.", nil)
#define BC_STRING_UPGRADE_TITLE NSLocalizedString(@"Confirm Upgrade", nil)
#define BC_STRING_UPGRADE_WARNING NSLocalizedString(@"Note that once upgraded, you cannot go back to the previous version, but all your bitcoin and your transaction history will be kept.", nil)
#define BC_STRING_CONFIRM_UPGRADE NSLocalizedString(@"Confirm Upgrade", nil)
#define BC_STRING_UPGRADE_NOW NSLocalizedString(@"Upgrade Now", nil)
#define BC_STRING_UPGRADE NSLocalizedString(@"Upgrade", nil)
#define BC_STRING_UPGRADE_SUCCESS_TITLE NSLocalizedString(@"Success!", nil)
#define BC_STRING_UPGRADE_SUCCESS NSLocalizedString(@"You are now running our most secure Bitcoin wallet", nil)
#define BC_STRING_UPGRADE_FEATURE_THREE NSLocalizedString(@"Customize the way you organize your bitcoin in your Blockchain Wallet", nil)
#define BC_STRING_UPGRADE_FEATURE_TWO NSLocalizedString(@"Easy one time wallet backup keeps you in control of your funds", nil)
#define BC_STRING_UPGRADE_FEATURE_ONE NSLocalizedString(@"Everything you need to store, spend and receive your bitcoin", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_TITLE NSLocalizedString(@"Upgrade Wallet", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_MESSAGE NSLocalizedString(@"We've included some significant privacy and security improvements. Once you click update you won't be able to go back to your old wallet", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_CANCEL_TITLE NSLocalizedString(@"Not now", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_UPDATE_TITLE NSLocalizedString(@"Update", nil)
#define BC_STRING_DONT_UPGRADE NSLocalizedString(@"or Continue", nil)
#define BC_STRING_UPGRADE_BUTTON_TITLE NSLocalizedString(@"UPGRADE YOUR WALLET", nil)
#define BC_STRING_ASK_ME_LATER NSLocalizedString(@"Ask Me Later", nil)

#define BC_STRING_SUPPORT_EMAIL_SUBJECT NSLocalizedString(@"iOS Support Request", nil)
#define BC_STRING_SUPPORT_INSTRUCTIONS NSLocalizedString(@"Please describe in detail the issue you are experiencing, along with any steps we can take to reproduce it.", nil)

#define BC_STRING_UNSAFE_DEVICE_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_UNSAFE_DEVICE_MESSAGE NSLocalizedString(@"Your device appears to be jailbroken. The security of your wallet may be compromised.", nil)

#define BC_STRING_ASK_TO_USE_OLD_WALLET_TITLE NSLocalizedString(@"We’ve detected a previous installation of Blockchain Wallet on your phone.", nil)
#define BC_STRING_ASK_TO_USE_OLD_WALLET_MESSAGE NSLocalizedString(@"Please choose from the options below.", nil)

#define BC_STRING_INVALID_ADDRESS NSLocalizedString(@"Address is not valid", nil)
#define BC_STRING_INVALID_ADDRESS_ARGUMENT NSLocalizedString(@"Invalid address: %@", nil)

#define BC_STRING_UPDATE NSLocalizedString(@"Update", nil)
#define BC_STRING_DISABLED NSLocalizedString (@"Disabled", nil)
#define BC_STRING_SECURITY_CENTER_INSTRUCTIONS NSLocalizedString(@"Complete the steps below for ultimate security", nil)
#define BC_STRING_SETTINGS_ACCOUNT_DETAILS NSLocalizedString(@"Account Details", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS NSLocalizedString(@"Notifications", nil)
#define BC_STRING_SETTINGS_EMAIL NSLocalizedString(@"Email", nil)
#define BC_STRING_SETTINGS_VERIFIED NSLocalizedString(@"Verified", nil)
#define BC_STRING_SETTINGS_UNVERIFIED NSLocalizedString(@"Unverified", nil)
#define BC_STRING_SETTINGS_UNCONFIRMED NSLocalizedString(@"Unconfirmed", nil)
#define BC_STRING_SETTINGS_STORED NSLocalizedString(@"Stored", nil)
#define BC_STRING_SETTINGS_NOT_STORED NSLocalizedString(@"Not Stored", nil)
#define BC_STRING_SETTINGS_PLEASE_ADD_EMAIL NSLocalizedString(@"Please add an email address", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER NSLocalizedString(@"Mobile Number", nil)
#define BC_STRING_SETTINGS_PREFERENCES NSLocalizedString(@"Preferences", nil)
#define BC_STRING_SETTINGS_DISPLAY_PREFERENCES NSLocalizedString(@"Display", nil)
#define BC_STRING_SETTINGS_FEES NSLocalizedString(@"Fees", nil)
#define BC_STRING_SETTINGS_FEE_PER_KB NSLocalizedString(@"Fee per KB", nil)
#define BC_STRING_SETTINGS_SECURITY NSLocalizedString(@"Security", nil)
#define BC_STRING_SETTINGS_SECURITY_USE_TOUCH_ID_AS_PIN NSLocalizedString(@"Use Touch ID as PIN", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION NSLocalizedString(@"2-step Verification", nil)
#define BC_STRING_ENABLE NSLocalizedString(@"Enable", nil)
#define BC_STRING_DISABLE NSLocalizedString(@"Disable", nil)
#define BC_STRING_SETTINGS_SECURITY_MUST_DISABLE_TWO_FACTOR_SMS_ARGUMENT NSLocalizedString(@"You must disable SMS 2-Step Verification before changing your mobile number (%@).", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_ENABLED_ARGUMENT NSLocalizedString(@"2-step Verification is currently enabled for %@.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_ENABLED NSLocalizedString(@"2-step Verification is currently enabled.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_DISABLED NSLocalizedString(@"2-step Verification is currently disabled.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_MESSAGE_SMS_ONLY NSLocalizedString(@"You can enable 2-step Verification via SMS on your mobile phone. In order to use other authentication methods instead, please login to our web wallet.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_GOOGLE NSLocalizedString(@"Google Authenticator", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_YUBI_KEY NSLocalizedString(@"Yubi Key", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_UNKNOWN NSLocalizedString(@"Unknown", nil)
#define BC_STRING_ENTER_ARGUMENT_TWO_FACTOR_CODE NSLocalizedString(@"Please enter your %@ 2FA code", nil)
#define BC_STRING_SETTINGS_SECURITY_PASSWORD_HINT NSLocalizedString(@"Password Hint", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT NSLocalizedString(@"Change Password Hint", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_WARNING_ALL_WHITESPACE NSLocalizedString(@"Your new password hint contains no text. Your password hint will be cleared.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_SUCCESS NSLocalizedString(@"Your password hint has been updated.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_INVALID_CHARACTERS NSLocalizedString(@"Your new password hint contains invalid characters. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_SAME_AS_PASSWORD NSLocalizedString(@"Your new password hint must be different from your password. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_SAME_AS_SECOND_PASSWORD NSLocalizedString(@"Your new password hint must be different from your second password. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD NSLocalizedString(@"Change Password", nil)
#define BC_STRING_SETTINGS_SECURITY_PASSWORD_CHANGED NSLocalizedString(@"Password changed. Please login to continue.", nil)
#define BC_STRING_SETTINGS_SECURITY_TOR_REQUESTS NSLocalizedString(@"Tor Requests", nil)
#define BC_STRING_SETTINGS_SECURITY_TOR_REQUESTS_BLOCKED NSLocalizedString(@"Tor requests are currently blocked.", nil)
#define BC_STRING_SETTINGS_SECURITY_TOR_REQUESTS_ALLOWED NSLocalizedString(@"Tor requests are currently allowed.", nil)
#define BC_STRING_BLOCK NSLocalizedString(@"Block", nil)
#define BC_STRING_BLOCK_TOR NSLocalizedString(@"Block Tor", nil)
#define BC_STRING_TOR_BLOCKED NSLocalizedString(@"Tor blocked", nil)
#define BC_STRING_TOR_ALLOWED NSLocalizedString(@"Tor requests allowed", nil)
#define BC_STRING_BLOCKED NSLocalizedString(@"Blocked", nil)
#define BC_STRING_ALLOW NSLocalizedString(@"Allow", nil)
#define BC_STRING_ALLOWED NSLocalizedString(@"Allowed", nil)
#define BC_STRING_SETTINGS_SECURITY_TOR_BLOCKING_DESCRIPTION NSLocalizedString(@"Enable this option to prevent IP addresses that are known to be part of the Tor anonymizing network from accessing your wallet. The Tor network is frequently used by hackers attempting to access Blockchain users' wallets.", nil)
#define BC_STRING_SETTINGS_LOCAL_CURRENCY NSLocalizedString(@"Local Currency", nil)
#define BC_STRING_SETTINGS_BTC NSLocalizedString(@"Bitcoin Unit", nil)
#define BC_STRING_SETTINGS_EMAIL_NOTIFICATIONS NSLocalizedString(@"Email Notifications", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_SETTINGS_EMAIL_FOOTER NSLocalizedString(@"Your verified email address is used to send login codes when suspicious or unusual activity is detected, to remind you of your wallet login ID, and to send bitcoin payment alerts when you receive funds. We will not use your email address for marketing purposes.", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_FOOTER NSLocalizedString(@"Enable notifications to receive an email whenever you receive bitcoin. Only labeled addresses and imported addresses are eligible to trigger notifications.", nil)
#define BC_STRING_SETTINGS_ABOUT NSLocalizedString(@"About", nil)
#define BC_STRING_SETTINGS_PRIVACY_POLICY NSLocalizedString(@"Privacy Policy", nil)
#define BC_STRING_SETTINGS_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_SETTINGS_VERIFY NSLocalizedString(@"Verify", nil)
#define BC_STRING_SETTINGS_SENT_TO_ARGUMENT NSLocalizedString(@"Sent to %@", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_SEND NSLocalizedString(@"Send verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_RESEND NSLocalizedString(@"Resend verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_ENTER_CODE NSLocalizedString(@"Enter your verification code", nil)
#define BC_STRING_ENTER_VERIFICATION_CODE NSLocalizedString(@"Enter Verification Code", nil)
#define BC_STRING_SETTINGS_VERIFY_EMAIL_RESEND NSLocalizedString(@"Resend verification email", nil)
#define BC_STRING_SETTINGS_VERIFY_INVALID_CODE NSLocalizedString(@"Invalid verification code. Please try again.", nil)
#define BC_STRING_SETTINGS_CHANGE_EMAIL NSLocalizedString(@"Change Email", nil)
#define BC_STRING_SETTINGS_NEW_EMAIL_ADDRESS NSLocalizedString(@"New Email Address", nil)
#define BC_STRING_SETTINGS_EMAIL_VERIFIED NSLocalizedString(@"Your email has been verified.", nil)
#define BC_STRING_SETTINGS_WALLET_ID NSLocalizedString (@"Wallet ID", nil)
#define BC_STRING_SETTINGS_WALLET_INFORMATION NSLocalizedString (@"Wallet Information", nil)
#define BC_STRING_SETTINGS_CHANGE_MOBILE_NUMBER NSLocalizedString(@"Change Mobile Number", nil)
#define BC_STRING_SETTINGS_NEW_MOBILE_NUMBER NSLocalizedString(@"New Mobile Number", nil)
#define BC_STRING_SETTINGS_ERROR_INVALID_MOBILE_NUMBER NSLocalizedString(@"Invalid mobile number.", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER_VERIFIED NSLocalizedString(@"Your mobile number has been verified.", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_TITLE NSLocalizedString(@"Error loading settings", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE NSLocalizedString(@"Please check your internet connection.", nil)
#define BC_STRING_SETTINGS_ERROR_UPDATING_TITLE NSLocalizedString(@"Error updating settings", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_TITLE NSLocalizedString(@"Change fee per kilobyte", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_MESSAGE_ARGUMENT NSLocalizedString(@"Current rate: %@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_ARGUMENT_BTC NSLocalizedString(@"%@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_TOO_HIGH NSLocalizedString(@"Fee is too high (0.01 BTC limit)", nil)
#define BC_STRING_SETTINGS_COPY_GUID NSLocalizedString(@"Copy Wallet ID", nil)
#define BC_STRING_SETTINGS_COPY_GUID_WARNING NSLocalizedString(@"Warning: Your wallet identifier is sensitive information. Copying it may compromise the security of your wallet.", nil)
#define BC_STRING_COPY_TO_CLIPBOARD NSLocalizedString(@"Copy to clipboard", nil)
#define BC_STRING_WARNING_FOR_ZERO_FEE NSLocalizedString(@"Transactions with no fees may take a long time to confirm or may not be confirmed at all. Would you like to continue?", nil)
#define BC_STRING_SETTINGS_ERROR_FEE_OUT_OF_RANGE NSLocalizedString(@"Please enter a fee greater than 0 BTC and at most 0.01 BTC", nil)

#define BC_STRING_VERIFY_EMAIL NSLocalizedString(@"Verify Email", nil)
#define BC_STRING_EMAIL_VERIFIED NSLocalizedString(@"Email Verified", nil)
#define BC_STRING_BACKUP_PHRASE NSLocalizedString(@"Backup Phrase", nil)
#define BC_STRING_WALLET_RECOVERY_PHRASE NSLocalizedString(@"Wallet Recovery Phrase", nil)
#define BC_STRING_PHRASE_BACKED NSLocalizedString(@"Phrase Backed", nil)
#define BC_STRING_LINK_MOBILE NSLocalizedString(@"Link Mobile", nil)
#define BC_STRING_MOBILE_LINKED NSLocalizedString(@"Mobile Linked", nil)
#define BC_STRING_STORE_HINT NSLocalizedString(@"Store Hint", nil)
#define BC_STRING_HINT_DESCRIPTION NSLocalizedString(@"We'll send the hint to your confirmed email address in case you request it.", nil)
#define BC_STRING_HINT_STORED NSLocalizedString(@"Hint Stored", nil)
#define BC_STRING_TWO_STEP_ENABLED_SUCCESS NSLocalizedString(@"2-Step has been enabled for SMS.", nil)
#define BC_STRING_TWO_STEP_DISABLED_SUCCESS NSLocalizedString(@"2-Step has been disabled.", nil)
#define BC_STRING_TWO_STEP_ERROR NSLocalizedString(@"An error occurred while changing 2-Step verification.", nil)
#define BC_STRING_TWO_STEP_ENABLED NSLocalizedString(@"2-Step Enabled", nil)
#define BC_STRING_ENABLE_TWO_STEP NSLocalizedString(@"Enable 2-Step", nil)
#define BC_STRING_ENABLE_TWO_STEP_SMS NSLocalizedString(@"Enable 2-Step for SMS", nil)

#define BC_STRING_NEW_ADDRESS NSLocalizedString(@"New Address", nil)
#define BC_STRING_NEW_ADDRESS_SCAN_QR_CODE NSLocalizedString(@"Scan QR code", nil)
#define BC_STRING_NEW_ADDRESS_CREATE_NEW NSLocalizedString(@"Create new address", nil)

#define BC_STRING_RECOVERY_PHRASE_ERROR_INSTRUCTIONS NSLocalizedString(@"Please enter your recovery phrase with words separated by spaces", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET NSLocalizedString(@"Recovering Funds", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_OF_ARGUMENT NSLocalizedString(@"Checking for more: Step %d of %d", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_ARGUMENT_FUNDS_ARGUMENT NSLocalizedString(@"Found %d, with %@", nil)
#define BC_STRING_LOADING_RECOVERY_CREATING_WALLET NSLocalizedString(@"Creating Wallet", nil)
#define BC_STRING_INVALID_RECOVERY_PHRASE NSLocalizedString(@"Invalid recovery phrase. Please try again", nil)

#define BC_STRING_MERCHANT_DIRECTORY_UNAVAILABLE NSLocalizedString(@"Merchant Directory is currently unavailable. Please try again later.", nil)
#define BC_STRING_SEND_ERROR_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection available. Please check your network settings.", nil)
#define BC_STRING_SEND_ERROR_FEE_TOO_LOW NSLocalizedString(@"The fee you have specified is too low.", nil)
#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)
#define BC_STRING_ENABLE_CAMERA_PERMISSIONS_ALERT_TITLE NSLocalizedString(@"Camera Access Denied", nil)
#define BC_STRING_ENABLE_CAMERA_PERMISSIONS_ALERT_MESSAGE NSLocalizedString(@"Blockchain does not have access to the camera. To enable access, go to your device Settings.", nil)

#define BC_STRING_TOUCH_ID_ERROR_VERIFYING_IDENTITY NSLocalizedString(@"There was a problem verifying your identity.", nil)
#define BC_STRING_TOUCH_ID_ERROR_WRONG_USER NSLocalizedString(@"Your identity does not match our records.", nil)
#define BC_STRING_TOUCH_ID_ERROR_NOT_AVAILABLE NSLocalizedString(@"Touch ID is not available on this device.", nil)
#define BC_STRING_TOUCH_ID_ERROR_MUST_ENABLE NSLocalizedString(@"Touch ID is not enabled on this device. To enable Touch ID, go to Settings->Touch ID & Passcode and add a fingerprint.", nil)
#define BC_STRING_TOUCH_ID_ERROR_LOCKED NSLocalizedString(@"Touch ID has been locked due to too many failed attempts.", nil)
#define BC_STRING_TOUCH_ID_ERROR_UNKNOWN_ARGUMENT NSLocalizedString(@"Unknown Touch ID error. Code: %ld", nil)
#define BC_STRING_TOUCH_ID_AUTHENTICATE NSLocalizedString(@"Authenticate with Touch ID", nil)
#define BC_STRING_TOUCH_ID_WARNING NSLocalizedString(@"Enabling this feature will allow all users with a registered Touch ID fingerprint on this device to access to your wallet.", nil)

#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)
#define BC_STRING_DEBUG NSLocalizedString(@"Debug", nil)
#define BC_STRING_SERVER_URL NSLocalizedString(@"Server URL", nil)
#define BC_STRING_WEBSOCKET_URL NSLocalizedString(@"WebSocket URL", nil)
#define BC_STRING_MERCHANT_URL NSLocalizedString(@"Merchant URL", nil)
#define BC_STRING_API_URL NSLocalizedString(@"API URL", nil)
#define BC_STRING_WALLET_JSON NSLocalizedString(@"Wallet JSON", nil)
#define BC_STRING_RESET_DONT_SHOW_AGAIN_PROMPT NSLocalizedString(@"Show all 'Dont Show Again' alerts", nil)
#define BC_STRING_RESET_DONT_SHOW_AGAIN_PROMPT_MESSAGE NSLocalizedString(@"This will allow the following alerts: Receive to watch-only, App Store review prompt, and Transfer All Funds.", nil)
#define BC_STRING_APP_STORE_REVIEW_PROMPT_TIMER NSLocalizedString(@"App Store review prompt timer (seconds)", nil)
#define BC_STRING_PLEASE_LOGIN NSLocalizedString(@"Please Login", nil)
#define BC_STRING_RESET NSLocalizedString(@"Reset", nil)
#define BC_STRING_FROM_LOWERCASE NSLocalizedString(@"from", nil)
#define BC_STRING_WELCOME NSLocalizedString(@"Welcome", nil)
#define BC_STRING_PIN NSLocalizedString(@"PIN", nil)

#define BC_STRING_MAKE_DEFAULT NSLocalizedString(@"Make Default", nil)
#define BC_STRING_DEFAULT NSLocalizedString(@"Default", nil)
#define BC_STRING_TRANSFER_FUNDS NSLocalizedString(@"Transfer Funds", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_ONE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_TRANSFER_FUNDS_DESCRIPTION_TWO NSLocalizedString(@"Your transferred funds will be safe and secure, and you'll benefit from increased privacy and convenient backup and recovery features.", nil)
#define BC_STRING_ARCHIVE_FOOTER_TITLE NSLocalizedString(@"Archive this if you do NOT want to use it anymore. Your funds will remain safe, and you can unarchive it at any time.", nil)
#define BC_STRING_ARCHIVED_FOOTER_TITLE NSLocalizedString(@"This is archived. Though you cannot send funds from here, any and all funds will remain safe. Simply unarchive to start using it again.", nil)
#define BC_STRING_TRANSFER_FOOTER_TITLE NSLocalizedString(@"For your safety, we recommend you to transfer any balances in your imported addresses into your Blockchain wallet.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE_ONE NSLocalizedString(@"If you are a merchant, show your xPub and use the Blockchain Merchant app to receive funds safely and privately.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_FOOTER_TITLE_TWO NSLocalizedString(@"Keep your xPub private. Someone with access to your xPub will be able to see all of your funds and transactions.", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_WARNING NSLocalizedString(@"Sharing your xPub authorizes others to track your transaction history. As authorized persons may be able to disrupt you from accessing your wallet, only share your xPub with people you trust.", nil)
#define BC_STRING_WATCH_ONLY_FOOTER_TITLE NSLocalizedString(@"This is a watch-only address. To spend your funds from this wallet, please scan your private key.", nil)
#define BC_STRING_SET_DEFAULT_ACCOUNT NSLocalizedString(@"Set as Default?", nil)
#define BC_STRING_AT_LEAST_ONE_ADDRESS_REQUIRED NSLocalizedString(@"You must have at least one active address", nil)
#define BC_STRING_EXTENDED_PUBLIC_KEY_DETAIL_HEADER_TITLE NSLocalizedString(@"Scan this code or copy it into your Blockchain Merchant app to securely receive Bitcoin.", nil)
#define BC_STRING_COPY_XPUB NSLocalizedString(@"Copy xPub", nil)
#define BC_STRING_ADDRESS_NOT_PRESENT_IN_WALLET NSLocalizedString(@"Your wallet does not contain this address.", nil)
#define BC_STRING_ADDRESS_NOT_WATCH_ONLY NSLocalizedString(@"This address is not watch-only.", nil)
#define BC_STRING_INCORRECT_PRIVATE_KEY_IMPORTED_MESSAGE_ONE NSLocalizedString(@"You've successfully imported a private key.", nil)
#define BC_STRING_INCORRECT_PRIVATE_KEY_IMPORTED_MESSAGE_TWO NSLocalizedString(@"NOTE: The scanned private key does not correspond to this watch-only address. If you want to spend from this address, make sure that you scan the correct private key.", nil)
#define BC_STRING_WRONG_BIP38_PASSWORD NSLocalizedString(@"Wrong BIP38 Password", nil)
#define BC_STRING_KEY_BELONGS_TO_OTHER_ADDRESS_NOT_WATCH_ONLY NSLocalizedString(@"This private key belongs to another address that is not watch only", nil)
#define BC_STRING_IMPORTED_PRIVATE_KEY_ARGUMENT NSLocalizedString(@"Imported Private Key %@", nil)
#define BC_STRING_IMPORTED_WATCH_ONLY_ADDRESS_ARGUMENT NSLocalizedString(@"Imported watch-only address %@", nil)
#define BC_STRING_IMPORTED_PRIVATE_KEY_SUCCESS NSLocalizedString(@"You can now spend from this address.", nil)
#define BC_STRING_IMPORTED_PRIVATE_KEY_TO_OTHER_ADDRESS_ARGUMENT NSLocalizedString(@"You've successfully imported the private key for ​the address %@, and you can now spend from it. If you want to spend from this address, make sure you scan the correct private key.", nil)
#define BC_STRING_ADD_WATCH_ONLY_ADDRESS_WARNING_ONE NSLocalizedString(@"You are about to import a watch-only address, an address (or public key script) stored in the wallet without the corresponding private key. This means that the funds can be spent ONLY if you have the private key stored elsewhere. If you do not have the private key stored, do NOT instruct anyone to send you bitcoin to the watch-only address.", nil)
#define BC_STRING_ADD_WATCH_ONLY_ADDRESS_WARNING_TWO NSLocalizedString(@"These options are recommended for advanced users only. Continue?", nil)
#define BC_STRING_UNKNOWN_KEY_FORMAT NSLocalizedString(@"Unknown key format", nil)
#define BC_STRING_NAME_ALREADY_IN_USE NSLocalizedString(@"This name is already in use. Please choose a different name.", nil)
#define BC_STRING_VERIFICATION_EMAIL_SENT_TO_ARGUMENT NSLocalizedString(@"Verification email has been sent to %@.", nil)
#define BC_STRING_PLEASE_CHECK_AND_CLICK_EMAIL_VERIFICATION_LINK NSLocalizedString(@"Please check your email and click on the verification link.", nil)
#define BC_STRING_ERROR_PLEASE_REFRESH_PAIRING_CODE NSLocalizedString(@"Please refresh the pairing code and try again.", nil)

#define BC_STRING_DONT_SHOW_AGAIN NSLocalizedString(@"Don't show again", nil)
#define BC_STRING_NOT_NOW NSLocalizedString(@"Not now", nil)
#define BC_STRING_INCORRECT_PRIVATE_KEY NSLocalizedString(@"Incorrect private key", nil)
#define BC_STRING_PRIVATE_KEY_NEEDED NSLocalizedString(@"Private Key Needed", nil)
#define BC_STRING_PRIVATE_KEY_NEEDED_MESSAGE_ARGUMENT NSLocalizedString(@"This action requires the private key for the Bitcoin address %@. Please scan the QR code.", nil)
#define BC_STRING_ENTER_ARGUMENT_AMOUNT NSLocalizedString(@"Enter %@ amount", nil)
#define BC_STRING_RETRIEVING_RECOMMENDED_FEE NSLocalizedString(@"Retrieving recommended fee", nil)
#define BC_STRING_FEE_HIGHER_THAN_RECOMMENDED_ARGUMENT_SUGGESTED_ARGUMENT NSLocalizedString(@"You specified an unusually high transaction fee of %@. Even if you lower the fee to %@, you can expect the transaction to confirm within the next 10 minutes (one block).", nil)
#define BC_STRING_FEE_LOWER_THAN_RECOMMENDED_ARGUMENT_SUGGESTED_ARGUMENT NSLocalizedString(@"You specified an exceptionally small transaction fee of %@. Your transaction may be stuck and possibly never be confirmed. To increase the likelihood for your transaction to confirm within approximately one hour (six blocks), we strongly recommend a fee of no less than %@.", nil)
#define BC_STRING_FEE_LOWER_THAN_RECOMMENDED_ARGUMENT_MUST_LOWER_AMOUNT_SUGGESTED_FEE_ARGUMENT_SUGGESTED_AMOUNT_ARGUMENT NSLocalizedString(@"You specified an exceptionally small transaction fee of %@. Your transaction may become stuck and possibly never confirm. To increase the likelihood for your transaction to confirm within approximately one hour (six blocks), we strongly recommend a fee of no less than %@. Since you don’t have sufficient funds, that means the Send amount will also have to be lowered to %@.", nil)
#define BC_STRING_INCREASE_FEE NSLocalizedString(@"Increase fee", nil)
#define BC_STRING_LOWER_FEE NSLocalizedString(@"Lower fee", nil)
#define BC_STRING_KEEP_HIGHER_FEE NSLocalizedString(@"Keep higher fee", nil)
#define BC_STRING_KEEP_LOWER_FEE NSLocalizedString(@"Keep lower fee", nil)
#define BC_STRING_USE_RECOMMENDED_VALUES NSLocalizedString(@"Use recommended values", nil)
#define BC_STRING_PLEASE_LOWER_CUSTOM_FEE NSLocalizedString(@"Please lower the fee to an amount that is less than your balance", nil)
#define BC_STRING_SIMULATE_SURGE NSLocalizedString(@"Simulate surge", nil)
#define BC_STRING_SURGE_OCCURRING_TITLE NSLocalizedString(@"Surge Occurring", nil)
#define BC_STRING_SURGE_OCCURRING_MESSAGE NSLocalizedString(@"The Bitcoin mining network is currently experiencing a high volume of activity, resulting in recommended fees that are higher than usual.", nil)
#define BC_STRING_FEE_INFORMATION_TITLE NSLocalizedString(@"Transaction Fees", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE NSLocalizedString(@"Transaction fees impact how quickly the Bitcoin mining network will confirm your transactions, and depend on the current network conditions.", nil)
#define BC_STRING_FEE_INFORMATION_MESSAGE_APPEND_REGULAR_SEND NSLocalizedString (@" We recommend the fee below for the transaction at this time.", nil)
#define BC_STRING_FEE_INFORMATION_DUST NSLocalizedString(@"This transaction requires a higher fee for dust consumption due to the small amount of change to be returned.", nil)

#define BC_STRING_APP_REVIEW_PROMPT_TITLE NSLocalizedString(@"Rate Blockchain Wallet", nil)
#define BC_STRING_YES_RATE_BLOCKCHAIN_WALLET NSLocalizedString(@"Yes, rate Blockchain Wallet", nil)
#define BC_STRING_APP_REVIEW_PROMPT_MESSAGE NSLocalizedString(@"Enjoying the Blockchain Wallet? Please take a moment to leave a review in the App Store and let others know about it.", nil)

#define BC_STRING_ERROR_SAVING_WALLET_CHECK_FOR_OTHER_DEVICES NSLocalizedString(@"An error occurred while saving your changes. Please make sure you are not logged into your wallet on another device.", nil)