//
//  LocalizationConstants.h
//  Blockchain
//
//  Created by Tim Lee on 8/6/14.
//  Copyright (c) 2014 Qkos Services Ltd. All rights reserved.
//
#import <Foundation/Foundation.h>

#define BC_STRING_ANY_ADDRESS NSLocalizedString(@"Any address", nil)

#define BC_STRING_YOU_MUST_ENTER_DESTINATION_ADDRESS NSLocalizedString(@"You must enter a destination address", nil)
#define BC_STRING_INVALID_TO_BITCOIN_ADDRESS NSLocalizedString(@"Invalid to bitcoin address", nil)
#define BC_STRING_FROM_TO_ACCOUNT_DIFFERENT NSLocalizedString(@"From and destination account have to be different", nil)
#define BC_STRING_FROM_TO_ADDRESS_DIFFERENT NSLocalizedString(@"From and destination address have to be different", nil)
#define BC_STRING_INVALID_SEND_VALUE NSLocalizedString(@"Invalid Send Value", nil)

#define BC_STRING_SIGNING_INPUTS NSLocalizedString(@"Signing Inputs", nil)
#define BC_STRING_SIGNING_INPUT NSLocalizedString(@"Signing Input %d", nil)
#define BC_STRING_FINISHED_SIGNING_INPUTS NSLocalizedString(@"Finished Signing Inputs", nil)

#define BC_STRING_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Add to Address book?", nil)
#define BC_STRING_NO NSLocalizedString(@"No", nil)
#define BC_STRING_YES NSLocalizedString(@"Yes", nil)
#define BC_STRING_SEND NSLocalizedString(@"Send", nil)
#define BC_STRING_NO_AVAILABLE_FUNDS NSLocalizedString(@"You have no available funds to send from this address", nil)
#define BC_STRING_MUST_BE_ABOVE_DUST_THRESHOLD NSLocalizedString(@"Amount must be above dust threshold (%lld Satoshi)", nil)
#define BC_STRING_RECEIVE NSLocalizedString(@"Receive", nil)
#define BC_STRING_SENDING_TRANSACTION NSLocalizedString(@"Sending Transaction", nil)
#define BC_STRING_USE_ALL_AMOUNT NSLocalizedString(@"Use all %@", nil)

#define BC_STRING_SUCCESS NSLocalizedString(@"Success", nil)
#define BC_STRING_PAYMENT_SENT NSLocalizedString(@"Payment Sent!", nil)
#define BC_STRING_PAYMENT_RECEIVED NSLocalizedString(@"Payment Received", nil)

#define BC_STRING_CONFIRM_PAYMENT NSLocalizedString(@"Confirm Payment", nil)
#define BC_STRING_ADJUST_FEE NSLocalizedString(@"Adjust Fee", nil)
#define BC_STRING_ASK_TO_ADD_TO_ADDRESS_BOOK NSLocalizedString(@"Would you like to add the bitcoin address %@ to your address book?", nil)
#define BC_STRING_ARGUMENT_COPIED_TO_CLIPBOARD NSLocalizedString(@"%@ copied to clipboard", nil)
#define BC_STRING_COPIED_TO_CLIPBOARD NSLocalizedString(@"Copied to clipboard", nil)
#define BC_STRING_CONFIRM_PAYMENT_OF NSLocalizedString(@"To: %@\n%@\nTotal Amount: %@\nFee: %@\n(%@)", nil)
#define BC_STRING_SEND_FROM NSLocalizedString(@"Send from...", nil)
#define BC_STRING_SEND_TO NSLocalizedString(@"Send to...", nil)
#define BC_STRING_CONFIRM_SWEEP_TITLE NSLocalizedString(@"Use all funds", nil)
#define BC_STRING_CONFIRM_SWEEP_MESSAGE_WANT_TO_SEND_ARGUMENT_BALANCE_MINUS_FEE_ARGUMENT_ARGUMENT_SEND_ARGUMENT NSLocalizedString(@"The amount you want to send (%@) is greater than the maximum amount you can spend minus the fee (%@ - %@). Would you like to send %@?", nil)

#define BC_STRING_YOU_MUST_ENTER_A_LABEL NSLocalizedString(@"You must enter a label", nil)
#define BC_STRING_LABEL_MUST_HAVE_LESS_THAN_18_CHAR NSLocalizedString(@"Label must have less than 18 characters", nil)
#define BC_STRING_LABEL_MUST_BE_ALPHANUMERIC NSLocalizedString(@"Label must contain letters and numbers only", nil)
#define BC_STRING_UNARCHIVE NSLocalizedString(@"Unarchive", nil)
#define BC_STRING_ARCHIVE NSLocalizedString(@"Archive", nil)
#define BC_STRING_NO_LABEL NSLocalizedString(@"No Label", nil)
#define BC_STRING_TRANSACTIONS_COUNT NSLocalizedString(@"%d Transactions", nil)
#define BC_STRING_LOADING_EXTERNAL_PAGE NSLocalizedString(@"Loading External Page", nil)

#define BC_STRING_PASSWORD_MUST_10_CHARACTERS_OR_LONGER NSLocalizedString(@"Password must 10 characters or longer", nil)
#define BC_STRING_PASSWORD_MINIMUM_10_CHARACTERS NSLocalizedString(@"* Minimum 10 characters", nil)
#define BC_STRING_PASSWORDS_DO_NOT_MATCH NSLocalizedString(@"Passwords do not match", nil)
#define BC_STRING_NEW_PASSWORD_MUST_BE_DIFFERENT NSLocalizedString(@"New password must be different", nil)
#define BC_STRING_PLEASE_PROVIDE_AN_EMAIL_ADDRESS NSLocalizedString(@"Please provide an email address.", nil)
#define BC_STRING_INVALID_EMAIL_ADDRESS NSLocalizedString(@"Invalid email address.", nil)
#define BC_STRING_DID_CREATE_NEW_ACCOUNT_DETAIL NSLocalizedString(@"Before accessing your wallet, please choose a pin number to use to unlock your wallet. It's important you remember this pin as it cannot be reset or changed without first unlocking the app.", nil)
#define BC_STRING_DID_CREATE_NEW_ACCOUNT_TITLE NSLocalizedString(@"Your wallet was successfully created.", nil)
#define BC_STRING_MY_BITCOIN_WALLET NSLocalizedString(@"My Bitcoin Wallet", nil)
#define BC_STRING_PASSWORD_STRENGTH_WEAK NSLocalizedString(@"Weak", nil)
#define BC_STRING_PASSWORD_STRENGTH_REGULAR NSLocalizedString(@"Regular", nil)
#define BC_STRING_PASSWORD_STRENGTH_NORMAL NSLocalizedString(@"Normal", nil)
#define BC_STRING_PASSWORD_STRENGTH_STRONG NSLocalizedString(@"Strong", nil)

#define BC_STRING_UNCONFIRMED NSLocalizedString(@"Unconfirmed", nil)
#define BC_STRING_COUNT_CONFIRMATIONS NSLocalizedString(@"%d Confirmations", nil)

#define BC_STRING_TRANSFERRED NSLocalizedString(@"Transferred", nil)
#define BC_STRING_RECEIVED NSLocalizedString(@"Received", nil)
#define BC_STRING_SENT NSLocalizedString(@"Sent", nil)

#define BC_STRING_ERROR NSLocalizedString(@"Error", nil)
#define BC_STRING_INVALID_AUTHENTICATION_TYPE NSLocalizedString(@"Invalid two-factor authentication type", nil)
#define BC_STRING_ERROR_LOADING_WALLET_IDENTIFIER_FROM_KEYCHAIN NSLocalizedString(@"An error was encountered retrieving your wallet identifier from the keychain. Please close the application and try again.", nil)
#define BC_STRING_ERROR_LOADING_WALLET NSLocalizedString(@"Unable to load wallet due to no server response. You may be offline or Blockchain is experiencing difficulties. Please try again later.", nil)

#define BC_STRING_INFORMATION NSLocalizedString(@"Information", nil)
#define BC_STRING_IMPORT_ADDRESS NSLocalizedString(@"Import Address", nil)
#define BC_STRING_IMPORTED_PRIVATE_KEY NSLocalizedString(@"Imported Private Key %@", nil)
#define BC_STRING_DECRYPTING_PRIVATE_KEY NSLocalizedString(@"Decrypting Private Key", nil)

#define BC_STRING_UNSUPPORTED_PRIVATE_KEY_FORMAT NSLocalizedString(@"Unsupported Private Key Format", nil)
#define BC_STRING_SCAN_PAIRING_CODE NSLocalizedString(@"Scan Pairing Code", nil)
#define BC_STRING_PARSING_PAIRING_CODE NSLocalizedString(@"Parsing Pairing Code", nil)
#define BC_STRING_INVALID_PAIRING_CODE NSLocalizedString(@"Invalid Pairing Code", nil)

#define BC_STRING_INSUFFICIENT_FUNDS NSLocalizedString(@"Insufficient Funds", nil)
#define BC_STRING_PLEASE_SELECT_DIFFERENT_ADDRESS_OR_FEE NSLocalizedString(@"Please select a different address to send from or lower the fee in Settings.", nil)

#define BC_STRING_OK NSLocalizedString(@"OK", nil)
#define BC_STRING_FAILED_TO_LOAD_WALLET_TITLE NSLocalizedString(@"Failed To Load Wallet", nil)
#define BC_STRING_WALLET_VERSION_NOT_SUPPORTED NSLocalizedString(@"Wallet version %lld not supported", nil)

#define BC_STRING_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection.", nil)
#define BC_STRING_TIMED_OUT NSLocalizedString(@"Connection timed out. Please check your internet connection.", nil)
#define BC_STRING_EMPTY_RESPONSE NSLocalizedString(@"Empty response from server.", nil)
#define BC_STRING_INVALID_RESPONSE NSLocalizedString(@"Invalid server response. Please check your internet connection.", nil)
#define BC_STRING_MAINTENANCE_MODE NSLocalizedString(@"Blockchain is currently down for maintenance. Please try again later.", nil)

#define BC_STRING_FAILED_TO_LOAD_WALLET_DETAIL NSLocalizedString(@"An error was encountered loading your wallet. You may be offline or Blockchain is experiencing difficulties. Please close the application and try again later or re-pair your device.", nil)
#define BC_STRING_FORGET_WALLET NSLocalizedString(@"Forget Wallet", nil)

#define BC_STRING_CLOSE_APP NSLocalizedString(@"Close App", nil)
#define BC_STRING_PRIVATE_KEY_ENCRYPTED_DESCRIPTION NSLocalizedString(@"The private key you are attempting to import is encrypted. Please enter the password below.", nil)

#define BC_STRING_NO_PASSWORD_ENTERED NSLocalizedString(@"No Password Entered", nil)
#define BC_STRING_SECOND_PASSWORD_INCORRECT NSLocalizedString(@"Second Password Incorrect", nil)

#define BC_STRING_ACTION_REQUIRES_SECOND_PASSWORD NSLocalizedString(@"This action requires the second password for your bitcoin wallet. Please enter it below and press continue.", nil)
#define BC_STRING_INVALID_GUID NSLocalizedString(@"Invalid GUID", nil)

#define BC_STRING_INVALID_SHARED_KEY NSLocalizedString(@"Invalid Shared Key", nil)
#define BC_STRING_ENTER_YOUR_CHARACTER_WALLET_IDENTIFIER NSLocalizedString(@"Please enter your 36 character wallet identifier correctly. It can be found in the welcome email on startup.", nil)
#define BC_STRING_INVALID_IDENTIFIER NSLocalizedString(@"Invalid Identifier", nil)

#define BC_STRING_DISABLE_TWO_FACTOR NSLocalizedString(@"You must have two-factor authentication disabled to pair manually.", nil)
#define BC_STRING_WALLET_PAIRED_SUCCESSFULLY_DETAIL NSLocalizedString(@"Before accessing your wallet, please choose a pin number to use to unlock your wallet. It's important you remember this pin as it cannot be reset or changed without first unlocking the app.", nil)
#define BC_STRING_WALLET_PAIRED_SUCCESSFULLY_TITLE NSLocalizedString(@"Wallet Paired Successfully.", nil)
#define BC_STRING_ASK_FOR_PRIVATE_KEY_TITLE NSLocalizedString(@"Scan Watch Only Address?", nil)
#define BC_STRING_ASK_FOR_PRIVATE_KEY_DETAIL NSLocalizedString(@"Wallet address %@ has funds available to spend. However the private key needs to be scanned from a paper wallet or QR Code. Would you like to scan the private key now?", nil)
#define BC_STRING_USER_DECLINED NSLocalizedString(@"User Declined", nil)
#define BC_STRING_CHANGE_PIN NSLocalizedString(@"Change PIN", nil)
#define BC_STRING_SETTINGS NSLocalizedString(@"Settings", nil)
#define BC_STRING_BACKUP NSLocalizedString(@"Backup", nil)
#define BC_STRING_ADD_EMAIL NSLocalizedString(@"Add Email", nil)
#define BC_STRING_NEWS_PRICE_CHARTS NSLocalizedString(@"News, Price & Charts", nil)
#define BC_STRING_LOGOUT NSLocalizedString(@"Logout", nil)
#define BC_STRING_REALLY_LOGOUT NSLocalizedString(@"Do you really want to log out?", nil)

#define BC_STRING_WARNING NSLocalizedString(@"Warning!!!", nil)
#define BC_STRING_FORGET_WALLET_DETAILS NSLocalizedString(@"This will erase all wallet data on this device. Please confirm you have your wallet information saved elsewhere otherwise any bitcoins in this wallet will be inaccessible!!", nil)
#define BC_STRING_CANCEL NSLocalizedString(@"Cancel", nil)
#define BC_STRING_HOW_WOULD_YOU_LIKE_TO_PAIR NSLocalizedString(@"How would you like to pair?", nil)
#define BC_STRING_MANUALLY NSLocalizedString(@"Manually", nil)
#define BC_STRING_AUTOMATICALLY NSLocalizedString(@"Automatically", nil)
#define BC_STRING_PIN_VALIDATION_ERROR NSLocalizedString(@"PIN Validation Error", nil)
#define BC_STRING_PLEASE_CHOOSE_ANOTHER_PIN NSLocalizedString(@"Please choose another PIN", nil)
#define BC_PIN_NO_MATCH NSLocalizedString(@"PINs do not match", nil)

#define BC_STRING_PIN_VALIDATION_ERROR_DETAIL NSLocalizedString(@"An error occurred validating your PIN code with the remote server. You may be offline or Blockchain may be experiencing difficulties. Would you like retry validation or instead enter your password manually?", nil)
#define BC_STRING_ENTER_PASSWORD NSLocalizedString(@"Enter Password", nil)
#define BC_STRING_ENTER_PIN NSLocalizedString(@"Enter PIN", nil)
#define BC_STRING_PLEASE_ENTER_PIN NSLocalizedString(@"Please enter your PIN", nil)
#define BC_STRING_PLEASE_ENTER_NEW_PIN NSLocalizedString(@"Please enter a new PIN", nil)
#define BC_STRING_CONFIRM_PIN NSLocalizedString(@"Confirm your PIN", nil)
#define BC_STRING_INCORRECT_PIN_RETRY NSLocalizedString(@"Incorrect PIN. Please retry.", nil)
#define RETRY_VALIDATION NSLocalizedString(@"Retry Validation", nil)
#define BC_STRING_PIN_VALIDATION_CANNOT_BE_COMPLETED NSLocalizedString(@"PIN Validation cannot be completed. Please enter your wallet password manually.", nil)
#define BC_STRING_PIN_RESPONSE_OBJECT_SUCCESS_LENGTH_0 NSLocalizedString(@"PIN Response Object success length 0", nil)
#define BC_STRING_DECRYPTED_PIN_PASSWORD_LENGTH_0 NSLocalizedString(@"Decrypted PIN Password length 0", nil)
#define BC_STRING_CANNOT_SAVE_PIN_CODE_WHILE NSLocalizedString(@"Cannot save PIN Code while wallet is not initialized or password is null", nil)
#define BC_STRING_INVALID_STATUS_CODE_RETURNED NSLocalizedString(@"Invalid Status Code Returned %@", nil)
#define BC_STRING_PIN_RESPONSE_OBJECT_KEY_OR_VALUE_LENGTH_0 NSLocalizedString(@"PIN Response Object key or value length 0", nil)
#define BC_STRING_PIN_ENCRYPTED_STRING_IS_NIL NSLocalizedString(@"PIN Encrypted String is nil", nil)
#define BC_STRING_PIN_SAVED_SUCCESSFULLY NSLocalizedString(@"PIN Saved Successfully", nil)
#define BC_STRING_WARNING_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_PIN_COMMON_CODE_WARNING_MESSAGE NSLocalizedString(@"The PIN you have selected is extremely common and may be easily guessed by someone with access to your phone within 3 tries. Would you like to use this PIN anyway?", nil)
#define BC_STRING_TRY_AGAIN NSLocalizedString(@"Try again", nil)

#define BC_STRING_PAYMENT_REQUEST NSLocalizedString(@"Please send payment to bitcoin address. FAQ: (https://blockchain.info/wallet/bitcoin-faq): %@", nil)
#define BC_STRING_PAYMENT_REQUEST_HTML NSLocalizedString(@"Please send payment to bitcoin address (<a href=\"https://blockchain.info/wallet/bitcoin-faq\">help?</a>): %@", nil)
#define BC_STRING_PAYMENT_REQUEST_SUBJECT NSLocalizedString(@"Bitcoin payment request", nil)
#define BC_STRING_CLOSE NSLocalizedString(@"Close", nil)

#define BC_STRING_CREATE_ACCOUNT NSLocalizedString(@"Create Account", nil)
#define BC_STRING_NAME_YOUR_ACCOUNT NSLocalizedString(@"Name your account", nil)
#define BC_STRING_EDIT_ACCOUNT NSLocalizedString(@"Edit Account", nil)
#define BC_STRING_LABEL NSLocalizedString(@"Label", nil)

#define BC_STRING_DONE NSLocalizedString(@"Done", nil)
#define BC_STRING_SAVE NSLocalizedString(@"Save", nil)
#define BC_STRING_CREATE_WALLET NSLocalizedString(@"Create Wallet", nil)

#define BC_STRING_MY_ACCOUNTS NSLocalizedString(@"My Accounts", nil)
#define BC_STRING_TOTAL_BALANCE NSLocalizedString(@"Total Balance", nil)
#define BC_STRING_IMPORTED_ADDRESSES NSLocalizedString(@"Imported Addresses", nil)
#define BC_STRING_IMPORTED_ADDRESSES_ARCHIVED NSLocalizedString(@"Imported Addresses (Archived)", nil)

#define BC_STRING_UPGRADE_TO_HD NSLocalizedString(@"Upgrade to HD", nil)
#define BC_STRING_UPGRADE_TO_V3 NSLocalizedString(@"Upgrade to V3", nil)

#define BC_STRING_ADDRESS_BOOK NSLocalizedString(@"Address book", nil)

#define BC_STRING_LOADING_VERIFYING NSLocalizedString (@"Verifying", nil)
#define BC_STRING_LOADING_DOWNLOADING_WALLET NSLocalizedString(@"Downloading Wallet", nil)
#define BC_STRING_LOADING_DECRYPTING_WALLET NSLocalizedString(@"Decrypting Wallet", nil)
#define BC_STRING_LOADING_LOADING_TRANSACTIONS NSLocalizedString(@"Loading transactions", nil)
#define BC_STRING_LOADING_LOADING_BUILD_HD_WALLET NSLocalizedString(@"Initializing Wallet", nil)
#define BC_STRING_LOADING_CHECKING_WALLET_UPDATES NSLocalizedString(@"Checking for Wallet updates", nil)
#define BC_STRING_LOADING_CREATING_HD_WALLET NSLocalizedString(@"Creating HD Wallet", nil)
#define BC_STRING_LOADING_CREATING_V3_WALLET NSLocalizedString(@"Creating V3 Wallet", nil)
#define BC_STRING_LOADING_CREATING_ACCOUNT NSLocalizedString(@"Creating Account", nil)
#define BC_STRING_LOADING_CREATING_WALLET NSLocalizedString(@"Creating new Wallet", nil)
#define BC_STRING_LOADING_IMPORT_KEY NSLocalizedString(@"Importing key", nil)
#define BC_STRING_LOADING_GENERATING_NEW_ADDRESS NSLocalizedString(@"Generating new address", nil)
#define BC_STRING_LOADING_SYNCING_WALLET NSLocalizedString(@"Syncing Wallet", nil)
#define BC_STRING_IDENTIFIER NSLocalizedString(@"Identifier", nil)

#define BC_STRING_MERCHANT_MAP NSLocalizedString(@"Merchant Map", nil)
#define BC_STRING_MERCHANT NSLocalizedString(@"Merchant", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_TITLE NSLocalizedString(@"Enable Location Services", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location.", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE_GLOBALLY_IOS_8_AND_ABOVE NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location. You can enable access in Settings->Privacy->Location Services", nil)
#define BC_STRING_MERCHANT_MAP_ASK_TO_ENABLE_LOCATION_SERVICES_ALERTVIEW_MESSAGE_GLOBALLY_IOS_7 NSLocalizedString(@"Blockchain needs Location Services enabled in order to access your location. You can enable access in Settings->Privacy->Location->Location Services", nil)
#define BC_STRING_GO_TO_SETTINGS NSLocalizedString(@"Go to Settings", nil)

#define BC_STRING_SUPPORT NSLocalizedString(@"Support", nil)

#define BC_STRING_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_TRANSACTION NSLocalizedString(@"Transaction", nil)
#define BC_STRING_AUTOMATIC_PAIRING NSLocalizedString(@"Automatic Pairing", nil)
#define BC_STRING_MANUAL_PAIRING NSLocalizedString(@"Manual Pairing", nil)
#define BC_STRING_MANUAL_PAIRING_AUTHORIZATION_REQUIRED_TITLE NSLocalizedString(@"Authorization Required", nil)
#define BC_STRING_MANUAL_PAIRING_AUTHORIZATION_REQUIRED_MESSAGE NSLocalizedString(@"Please check your email.", nil)
#define BC_STRING_PASSWORD_REQUIRED NSLocalizedString(@"Password Required", nil)
#define BC_STRING_INCORRECT_PASSWORD NSLocalizedString(@"Incorrect password", nil)
#define BC_STRING_SECOND_PASSWORD_REQUIRED NSLocalizedString(@"Second Password Required", nil)
#define BC_STRING_CREATE_NEW_WALLET NSLocalizedString(@"Create New Wallet", nil)
#define BC_STRING_REQUEST_AMOUNT NSLocalizedString(@"Request Amount", nil)
#define BC_STRING_LABEL_ADDRESS NSLocalizedString(@"Label Address", nil)
#define BC_STRING_SCAN_QR_CODE NSLocalizedString(@"Scan QR Code", nil)
#define BC_STRING_SCAN_PRIVATE_KEY NSLocalizedString(@"Scan Private Key", nil)
#define BC_STRING_CONTINUE NSLocalizedString(@"Continue", nil)

#define BC_STRING_LOG_IN_TO_WALLET NSLocalizedString(@"Log in to my Wallet", nil)
#define BC_STRING_LOGIN_EXISTING_WALLET NSLocalizedString(@"Login existing Wallet", nil)
#define BC_STRING_RECOVER_FUNDS NSLocalizedString(@"Recover Funds", nil)
#define BC_STRING_RECOVER_FUNDS_ONLY_IF_FORGOT_CREDENTIALS NSLocalizedString(@"You should always pair or login if you have access to your GUID and password. Recovering your funds will create a new GUID. Would you like to continue?", nil)

#define BC_STRING_COPY_ADDRESS NSLocalizedString(@"Copy Address", nil)
#define BC_STRING_ARCHIVE_ADDRESS NSLocalizedString(@"Archive Address", nil)
#define BC_STRING_UNARCHIVE_ADDRESS NSLocalizedString(@"Unarchive Address", nil)

#define BC_STRING_AT_LEAST_ONE_ACTIVE_ADDRESS NSLocalizedString(@"You must leave at least one active address", nil)

#define BC_STRING_UPGRADE_TEXT NSLocalizedString(@"We've designed a whole new\nwallet experience for you", nil)
#define BC_STRING_UPGRADE_NOW NSLocalizedString(@"Upgrade Now", nil)
#define BC_STRING_UPGRADE_SUCCESS_TITLE NSLocalizedString(@"Success!", nil)
#define BC_STRING_UPGRADE_SUCCESS NSLocalizedString(@"You are now running our most secure Bitcoin wallet", nil)
#define BC_STRING_UPGRADE_FEATURE_THREE NSLocalizedString(@"Create personalized accounts to help keep your wallet organized", nil)
#define BC_STRING_UPGRADE_FEATURE_TWO NSLocalizedString(@"Easy one time wallet backup keeps you in control of your funds", nil)
#define BC_STRING_UPGRADE_FEATURE_ONE NSLocalizedString(@"Anything you need to store, spend and receive your bitcoin", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_TITLE NSLocalizedString(@"Upgrade Wallet", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_MESSAGE NSLocalizedString(@"We've included some significant privacy and security improvements. Once you click update you won't be able to go back to your old wallet", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_CANCEL_TITLE NSLocalizedString(@"Not now", nil)
#define BC_STRING_UPGRADE_ALERTVIEW_UPDATE_TITLE NSLocalizedString(@"Update", nil)
#define BC_STRING_DONT_UPGRADE NSLocalizedString(@"or Continue", nil)
#define BC_STRING_UPGRADE_BUTTON_TITLE NSLocalizedString(@"UPGRADE YOUR WALLET", nil)
#define BC_STRING_UPGRADE_ASKLATER_TITLE NSLocalizedString(@"Ask Me Later", nil)

#define BC_STRING_SUPPORT_EMAIL_SUBJECT NSLocalizedString(@"iOS Support Request", nil)
#define BC_STRING_SUPPORT_INSTRUCTIONS NSLocalizedString(@"Please describe in detail the issue you are experiencing, along with any steps we can take to reproduce it.", nil)

#define BC_STRING_UNSAFE_DEVICE_TITLE NSLocalizedString(@"Warning", nil)
#define BC_STRING_UNSAFE_DEVICE_MESSAGE NSLocalizedString(@"Your device appears to be jailbroken. The security of your wallet may be compromised.", nil)

#define BC_STRING_ASK_TO_USE_OLD_WALLET_TITLE NSLocalizedString(@"We’ve detected a previous installation of Blockchain Wallet on your phone.", nil)
#define BC_STRING_ASK_TO_USE_OLD_WALLET_MESSAGE NSLocalizedString(@"Please choose from the options below.", nil)

#define BC_STRING_INVALID_ADDRESS NSLocalizedString(@"Address is not valid", nil)
#define BC_STRING_INVALID_ADDRESS_ARGUMENT NSLocalizedString(@"Invalid address: %@", nil)

#define BC_STRING_UPDATE NSLocalizedString(@"Update", nil)
#define BC_STRING_DISABLED NSLocalizedString (@"Disabled", nil)
#define BC_STRING_SETTINGS_ACCOUNT_DETAILS NSLocalizedString(@"Account Details", nil)
#define BC_STRING_SETTINGS_EMAIL NSLocalizedString(@"Email", nil)
#define BC_STRING_SETTINGS_VERIFIED NSLocalizedString(@"Verified", nil)
#define BC_STRING_SETTINGS_UNVERIFIED NSLocalizedString(@"Unverified", nil)
#define BC_STRING_SETTINGS_STORED NSLocalizedString(@"Stored", nil)
#define BC_STRING_SETTINGS_NOT_STORED NSLocalizedString(@"Not Stored", nil)
#define BC_STRING_SETTINGS_PLEASE_ADD_EMAIL NSLocalizedString(@"Please add an email address", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER NSLocalizedString(@"Mobile Number", nil)
#define BC_STRING_SETTINGS_DISPLAY_PREFERENCES NSLocalizedString(@"Display", nil)
#define BC_STRING_SETTINGS_FEES NSLocalizedString(@"Fees", nil)
#define BC_STRING_SETTINGS_FEE_PER_KB NSLocalizedString(@"Fee per KB", nil)
#define BC_STRING_SETTINGS_SECURITY NSLocalizedString(@"Security", nil)
#define BC_STRING_SETTINGS_SECURITY_USE_TOUCH_ID_AS_PIN NSLocalizedString(@"Use Touch ID as PIN", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION NSLocalizedString(@"2-step Verification", nil)
#define BC_STRING_ENABLE NSLocalizedString(@"Enable", nil)
#define BC_STRING_DISABLE NSLocalizedString(@"Disable", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_ENABLED_ARGUMENT NSLocalizedString(@"2-step Verification is currently enabled for %@.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_DISABLED NSLocalizedString(@"2-step Verification is currently disabled.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_MESSAGE_SMS_ONLY NSLocalizedString(@"You can enable 2-step Verification via SMS on your mobile phone. In order to use Google Authenticator instead, please login to our web wallet.", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_GOOGLE NSLocalizedString(@"Google Authenticator", nil)
#define BC_STRING_SETTINGS_SECURITY_TWO_STEP_VERIFICATION_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_ENTER_TWO_FACTOR_CODE NSLocalizedString(@"Please enter your 2FA code", nil)
#define BC_STRING_SETTINGS_SECURITY_PASSWORD_HINT NSLocalizedString(@"Password Hint", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT NSLocalizedString(@"Change Password Hint", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_WARNING_ALL_WHITESPACE NSLocalizedString(@"Your new password hint contains no text. Your password hint will be cleared.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_SUCCESS NSLocalizedString(@"Your password hint has been updated.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_INVALID_CHARACTERS NSLocalizedString(@"Your new password hint contains invalid characters. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_SAME_AS_PASSWORD NSLocalizedString(@"Your new password hint must be different from your password. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD_HINT_ERROR_SAME_AS_SECOND_PASSWORD NSLocalizedString(@"Your new password hint must be different from your second password. Please try again.", nil)
#define BC_STRING_SETTINGS_SECURITY_CHANGE_PASSWORD NSLocalizedString(@"Change Password", nil)
#define BC_STRING_SETTINGS_SECURITY_PASSWORD_CHANGED NSLocalizedString(@"Password changed. Please login to continue.", nil)
#define BC_STRING_SETTINGS_LOCAL_CURRENCY NSLocalizedString(@"Local Currency", nil)
#define BC_STRING_SETTINGS_BTC NSLocalizedString(@"Bitcoin Unit", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS NSLocalizedString(@"Notifications", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_SMS NSLocalizedString(@"SMS", nil)
#define BC_STRING_SETTINGS_EMAIL_FOOTER NSLocalizedString(@"An email account is needed to help recover a lost wallet identifier and for payment notifications. Also, your verified email address will be used as a second layer of verification when you log into your wallet.", nil)
#define BC_STRING_SETTINGS_NOTIFICATIONS_FOOTER NSLocalizedString(@"Optionally receive notifications when a payment is sent or received from your wallet.", nil)
#define BC_STRING_SETTINGS_ABOUT NSLocalizedString(@"About", nil)
#define BC_STRING_SETTINGS_PRIVACY_POLICY NSLocalizedString(@"Privacy Policy", nil)
#define BC_STRING_SETTINGS_TERMS_OF_SERVICE NSLocalizedString(@"Terms of Service", nil)
#define BC_STRING_SETTINGS_VERIFY NSLocalizedString(@"Verify", nil)
#define BC_STRING_SETTINGS_SENT_TO_ARGUMENT NSLocalizedString(@"Sent to %@", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_SEND NSLocalizedString(@"Send verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_MOBILE_RESEND NSLocalizedString(@"Resend verification SMS", nil)
#define BC_STRING_SETTINGS_VERIFY_ENTER_CODE NSLocalizedString(@"Enter your verification code", nil)
#define BC_STRING_ENTER_VERIFICATION_CODE NSLocalizedString(@"Enter Verification Code", nil)
#define BC_STRING_SETTINGS_VERIFY_EMAIL_RESEND NSLocalizedString(@"Resend verification email", nil)
#define BC_STRING_SETTINGS_VERIFY_INVALID_CODE NSLocalizedString(@"Invalid verification code. Please try again.", nil)
#define BC_STRING_SETTINGS_CHANGE_EMAIL NSLocalizedString(@"Change Email", nil)
#define BC_STRING_SETTINGS_NEW_EMAIL_ADDRESS NSLocalizedString(@"New Email Address", nil)
#define BC_STRING_SETTINGS_EMAIL_VERIFIED NSLocalizedString(@"Your email has been verified.", nil)
#define BC_STRING_SETTINGS_WALLET_ID NSLocalizedString (@"Wallet ID", nil)
#define BC_STRING_SETTINGS_CHANGE_MOBILE_NUMBER NSLocalizedString(@"Change Mobile Number", nil)
#define BC_STRING_SETTINGS_NEW_MOBILE_NUMBER NSLocalizedString(@"New Mobile Number", nil)
#define BC_STRING_SETTINGS_ERROR_INVALID_MOBILE_NUMBER NSLocalizedString(@"Invalid mobile number.", nil)
#define BC_STRING_SETTINGS_MOBILE_NUMBER_VERIFIED NSLocalizedString(@"Your mobile number has been verified.", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_TITLE NSLocalizedString(@"Error loading settings", nil)
#define BC_STRING_SETTINGS_ERROR_LOADING_MESSAGE NSLocalizedString(@"Please check your internet connection.", nil)
#define BC_STRING_SETTINGS_ERROR_UPDATING_TITLE NSLocalizedString(@"Error updating settings", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_TITLE NSLocalizedString(@"Change fee per kilobyte", nil)
#define BC_STRING_SETTINGS_CHANGE_FEE_MESSAGE_ARGUMENT NSLocalizedString(@"Current rate: %@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_ARGUMENT_BTC NSLocalizedString(@"%@ BTC", nil)
#define BC_STRING_SETTINGS_FEE_TOO_HIGH NSLocalizedString(@"Fee is too high (0.01 BTC limit)", nil)
#define BC_STRING_SETTINGS_COPY_GUID NSLocalizedString(@"Copy GUID", nil)
#define BC_STRING_SETTINGS_COPY_GUID_WARNING NSLocalizedString(@"Warning: Your wallet identifier is sensitive information. Copying it may compromise the security of your wallet.", nil)
#define BC_STRING_COPY_TO_CLIPBOARD NSLocalizedString(@"Copy to clipboard", nil)
#define BC_STRING_WARNING_FOR_ZERO_FEE NSLocalizedString(@"Transactions with no fees may take a long time to confirm or may not be confirmed at all. Would you like to continue?", nil)
#define BC_STRING_SETTINGS_ERROR_FEE_OUT_OF_RANGE NSLocalizedString(@"Please enter a fee greater than 0 BTC and at most 0.01 BTC", nil)

#define BC_STRING_NEW_ADDRESS NSLocalizedString(@"New Address", nil)
#define BC_STRING_NEW_ADDRESS_SCAN_QR_CODE NSLocalizedString(@"Scan QR code", nil)
#define BC_STRING_NEW_ADDRESS_GENERATE_NEW NSLocalizedString(@"Generate new", nil)

#define BC_STRING_RECOVERY_PHRASE_ERROR_INSTRUCTIONS NSLocalizedString(@"Please enter your recovery phrase with words separated by spaces", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET NSLocalizedString(@"Recovering Funds", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_CHECKING_ARGUMENT_TEN_ACCOUNTS NSLocalizedString(@"Checking for more accounts: Step %d of 10", nil)
#define BC_STRING_LOADING_RECOVERING_WALLET_ACCOUNT_ARGUMENT_FUNDS_ARGUMENT NSLocalizedString(@"Found account %d, with %@", nil)
#define BC_STRING_LOADING_RECOVERY_CREATING_WALLET NSLocalizedString(@"Creating Wallet", nil)
#define BC_STRING_INVALID_RECOVERY_PHRASE NSLocalizedString(@"Invalid recovery phrase. Please try again", nil)

#define BC_STRING_MERCHANT_DIRECTORY_UNAVAILABLE NSLocalizedString(@"Merchant Directory is currently unavailable. Please try again later.", nil)
#define BC_STRING_SEND_ERROR_NO_INTERNET_CONNECTION NSLocalizedString(@"No internet connection available. Please check your network settings.", nil)
#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)
#define BC_STRING_ENABLE_CAMERA_PERMISSIONS_ALERT_TITLE NSLocalizedString(@"Camera Access Denied", nil)
#define BC_STRING_ENABLE_CAMERA_PERMISSIONS_ALERT_MESSAGE NSLocalizedString(@"Blockchain does not have access to the camera. To enable access, go to your device Settings.", nil)

#define BC_STRING_TOUCH_ID_ERROR_VERIFYING_IDENTITY NSLocalizedString(@"There was a problem verifying your identity.", nil)
#define BC_STRING_TOUCH_ID_ERROR_WRONG_USER NSLocalizedString(@"Your identity does not match our records.", nil)
#define BC_STRING_TOUCH_ID_ERROR_NOT_AVAILABLE NSLocalizedString(@"Touch ID is not available on this device.", nil)
#define BC_STRING_TOUCH_ID_ERROR_MUST_ENABLE NSLocalizedString(@"Touch ID is not enabled on this device. To enable Touch ID, go to Settings->Touch ID & Passcode and add a fingerprint.", nil)
#define BC_STRING_TOUCH_ID_ERROR_LOCKED NSLocalizedString(@"Touch ID has been locked due to too many failed attempts.", nil)
#define BC_STRING_TOUCH_ID_ERROR_UNKNOWN_ARGUMENT NSLocalizedString(@"Unknown Touch ID error. Code: %ld", nil)
#define BC_STRING_TOUCH_ID_AUTHENTICATE NSLocalizedString(@"Authenticate with Touch ID", nil)
#define BC_STRING_TOUCH_ID_WARNING NSLocalizedString(@"Enabling this feature will allow all users with a registered Touch ID fingerprint on this device to access to your wallet.", nil)

#define BC_STRING_NO_EMAIL_CONFIGURED NSLocalizedString(@"You do not have an account set up for Mail. Please contact %@", nil)